# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sa2005.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(614, 495)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(608, 495))
        MainWindow.setMaximumSize(QtCore.QSize(9999, 9999))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_control_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_control_frame.setEnabled(True)
        self.main_control_frame.setGeometry(QtCore.QRect(250, 0, 351, 401))
        self.main_control_frame.setObjectName("main_control_frame")
        self.gridFrame = QtWidgets.QFrame(self.main_control_frame)
        self.gridFrame.setGeometry(QtCore.QRect(190, 1, 161, 391))
        self.gridFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gridFrame.setLineWidth(1)
        self.gridFrame.setMidLineWidth(0)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridFrame1 = QtWidgets.QFrame(self.gridFrame)
        self.gridFrame1.setMinimumSize(QtCore.QSize(152, 74))
        self.gridFrame1.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame1.setLineWidth(2)
        self.gridFrame1.setObjectName("gridFrame1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_hot_open = QtWidgets.QPushButton(self.gridFrame1)
        self.button_hot_open.setObjectName("button_hot_open")
        self.gridLayout_3.addWidget(self.button_hot_open, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridFrame1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 2, 1)
        self.button_hot_closed = QtWidgets.QPushButton(self.gridFrame1)
        self.button_hot_closed.setObjectName("button_hot_closed")
        self.gridLayout_3.addWidget(self.button_hot_closed, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.gridFrame1, 0, 0, 1, 1)
        self.gridFrame_2 = QtWidgets.QFrame(self.gridFrame)
        self.gridFrame_2.setMinimumSize(QtCore.QSize(152, 74))
        self.gridFrame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_2.setLineWidth(2)
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_neutral_open = QtWidgets.QPushButton(self.gridFrame_2)
        self.button_neutral_open.setObjectName("button_neutral_open")
        self.gridLayout_4.addWidget(self.button_neutral_open, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 2, 1)
        self.button_neutral_closed = QtWidgets.QPushButton(self.gridFrame_2)
        self.button_neutral_closed.setObjectName("button_neutral_closed")
        self.gridLayout_4.addWidget(self.button_neutral_closed, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.gridFrame_2, 1, 0, 1, 1)
        self.gridFrame_3 = QtWidgets.QFrame(self.gridFrame)
        self.gridFrame_3.setMinimumSize(QtCore.QSize(152, 74))
        self.gridFrame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_3.setLineWidth(2)
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_8 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 2, 1)
        self.button_ground_closed = QtWidgets.QPushButton(self.gridFrame_3)
        self.button_ground_closed.setObjectName("button_ground_closed")
        self.gridLayout_10.addWidget(self.button_ground_closed, 0, 1, 1, 1)
        self.button_ground_open = QtWidgets.QPushButton(self.gridFrame_3)
        self.button_ground_open.setObjectName("button_ground_open")
        self.gridLayout_10.addWidget(self.button_ground_open, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.gridFrame_3, 2, 0, 1, 1)
        self.gridFrame_4 = QtWidgets.QFrame(self.gridFrame)
        self.gridFrame_4.setMinimumSize(QtCore.QSize(152, 74))
        self.gridFrame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_4.setLineWidth(2)
        self.gridFrame_4.setObjectName("gridFrame_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridFrame_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.button_polarity_rev = QtWidgets.QPushButton(self.gridFrame_4)
        self.button_polarity_rev.setObjectName("button_polarity_rev")
        self.gridLayout_11.addWidget(self.button_polarity_rev, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridFrame_4)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 0, 0, 2, 1)
        self.button_polarity_fwd = QtWidgets.QPushButton(self.gridFrame_4)
        self.button_polarity_fwd.setObjectName("button_polarity_fwd")
        self.gridLayout_11.addWidget(self.button_polarity_fwd, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.gridFrame_4, 3, 0, 1, 1)
        self.verticalFrame = QtWidgets.QFrame(self.main_control_frame)
        self.verticalFrame.setEnabled(True)
        self.verticalFrame.setGeometry(QtCore.QRect(10, 0, 171, 391))
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_mains_voltage = QtWidgets.QPushButton(self.verticalFrame)
        self.button_mains_voltage.setObjectName("button_mains_voltage")
        self.verticalLayout.addWidget(self.button_mains_voltage)
        self.button_device_current = QtWidgets.QPushButton(self.verticalFrame)
        self.button_device_current.setObjectName("button_device_current")
        self.verticalLayout.addWidget(self.button_device_current)
        self.button_earth_resistance = QtWidgets.QPushButton(self.verticalFrame)
        self.button_earth_resistance.setObjectName("button_earth_resistance")
        self.verticalLayout.addWidget(self.button_earth_resistance)
        self.button_earth_ground = QtWidgets.QPushButton(self.verticalFrame)
        self.button_earth_ground.setObjectName("button_earth_ground")
        self.verticalLayout.addWidget(self.button_earth_ground)
        self.button_enclosure = QtWidgets.QPushButton(self.verticalFrame)
        self.button_enclosure.setObjectName("button_enclosure")
        self.verticalLayout.addWidget(self.button_enclosure)
        self.button_lead_to_earth = QtWidgets.QPushButton(self.verticalFrame)
        self.button_lead_to_earth.setObjectName("button_lead_to_earth")
        self.verticalLayout.addWidget(self.button_lead_to_earth)
        self.button_lead_to_lead = QtWidgets.QPushButton(self.verticalFrame)
        self.button_lead_to_lead.setObjectName("button_lead_to_lead")
        self.verticalLayout.addWidget(self.button_lead_to_lead)
        self.button_lead_isolation = QtWidgets.QPushButton(self.verticalFrame)
        self.button_lead_isolation.setObjectName("button_lead_isolation")
        self.verticalLayout.addWidget(self.button_lead_isolation)
        self.button_external = QtWidgets.QPushButton(self.verticalFrame)
        self.button_external.setObjectName("button_external")
        self.verticalLayout.addWidget(self.button_external)
        self.button_console_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_console_clear.setGeometry(QtCore.QRect(10, 400, 75, 23))
        self.button_console_clear.setObjectName("button_console_clear")
        self.port_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.port_combo_box.setGeometry(QtCore.QRect(330, 440, 101, 22))
        self.port_combo_box.setObjectName("port_combo_box")
        self.button_port_connect = QtWidgets.QPushButton(self.centralwidget)
        self.button_port_connect.setGeometry(QtCore.QRect(440, 440, 75, 23))
        self.button_port_connect.setObjectName("button_port_connect")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 440, 31, 16))
        self.label_2.setObjectName("label_2")
        self.checkbox_show_commands = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_show_commands.setGeometry(QtCore.QRect(100, 400, 131, 17))
        self.checkbox_show_commands.setObjectName("checkbox_show_commands")
        self.button_port_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.button_port_refresh.setGeometry(QtCore.QRect(520, 440, 75, 23))
        self.button_port_refresh.setObjectName("button_port_refresh")
        self.console_output = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.console_output.setGeometry(QtCore.QRect(10, 100, 241, 291))
        self.console_output.setReadOnly(True)
        self.console_output.setObjectName("console_output")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setEnabled(True)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 0, 241, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SA-2005 Control Panel"))
        self.button_hot_open.setText(_translate("MainWindow", "OPEN"))
        self.label.setText(_translate("MainWindow", "HOT"))
        self.button_hot_closed.setText(_translate("MainWindow", "CLOSED"))
        self.button_neutral_open.setText(_translate("MainWindow", "OPEN"))
        self.label_5.setText(_translate("MainWindow", "NEUTRAL"))
        self.button_neutral_closed.setText(_translate("MainWindow", "CLOSED"))
        self.label_8.setText(_translate("MainWindow", "GROUND"))
        self.button_ground_closed.setText(_translate("MainWindow", "CLOSED"))
        self.button_ground_open.setText(_translate("MainWindow", "OPEN"))
        self.button_polarity_rev.setText(_translate("MainWindow", "REV"))
        self.label_9.setText(_translate("MainWindow", "POLARITY"))
        self.button_polarity_fwd.setText(_translate("MainWindow", "FWD"))
        self.button_mains_voltage.setText(_translate("MainWindow", "MAINS VOLTAGE"))
        self.button_device_current.setText(_translate("MainWindow", "DEVICE CURRENT"))
        self.button_earth_resistance.setText(_translate("MainWindow", "EARTH RESISTANCE"))
        self.button_earth_ground.setText(_translate("MainWindow", "EARTH / GROUND"))
        self.button_enclosure.setText(_translate("MainWindow", "ENCLOSURE"))
        self.button_lead_to_earth.setText(_translate("MainWindow", "LEAD TO EARTH"))
        self.button_lead_to_lead.setText(_translate("MainWindow", "LEAD TO LEAD"))
        self.button_lead_isolation.setText(_translate("MainWindow", "LEAD ISOLATION"))
        self.button_external.setText(_translate("MainWindow", "EXTERNAL"))
        self.button_console_clear.setText(_translate("MainWindow", "Clear"))
        self.button_port_connect.setText(_translate("MainWindow", "Connect"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.checkbox_show_commands.setText(_translate("MainWindow", "Show raw commands"))
        self.button_port_refresh.setText(_translate("MainWindow", "Refresh"))
        self.console_output.setPlaceholderText(_translate("MainWindow", "Console Output"))
